# Generated by Django 3.0.6 on 2020-05-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccine',
            new_name='vaccinations',
        ),
    ]
